const Sequelize=require('sequelize')
const {sequelize}=require('../db')

const BillingModel=sequelize.define('billings',{
    id:{
        type:Sequelize.INTEGER,
        autoIncrement:true,
        primaryKey:true,  
    },
    billing_id:{
        type:Sequelize.STRING
    },
    amount:{
        type:Sequelize.INTEGER
    },
    detraction:{
        type:Sequelize.INTEGER
    },
    net_amount:{
        type:Sequelize.INTEGER
    },
    account:{
        type:Sequelize.INTEGER
    },
    file_link:{
        type:Sequelize.STRING
    },
    contactName:{
        type:Sequelize.STRING
    },
    date_emission:{
        type:Sequelize.STRING
    },
    status:{
        type:Sequelize.STRING
    },
    date_payment:{
        type:Sequelize.STRING
    },
    n_days:{
        type:Sequelize.INTEGER
    },
    monthly_fee:{
        type:Sequelize.STRING
    },
    commission:{
        type:Sequelize.STRING
    },
    partnet:{
        type:Sequelize.STRING
    },
    first_payment:{
        type:Sequelize.STRING
    },
    second_payment:{
        type:Sequelize.STRING
    },
    commercial:{
        type:Sequelize.STRING
    },
    n_commercial_qipu:{
        type:Sequelize.STRING
    },
    bank_name:{
        type:Sequelize.STRING
    }
})

module.exports=BillingModel