
module.exports=(sequelize,type)=>{
    return sequelize.define('users',{
        id:{
            type:type.INTEGER,
            autoIncrement:true,
            primaryKey:true,
        },
        name:{
            type:type.STRING,
        },
        password:{
            type:type.STRING(150)
        },
        email:{
            type:type.STRING
        },
        status:{
            type:type.BOOLEAN,
            defaultValue:true
        },
        role:{
            type:type.INTEGER,
            defaultValue:2
        },
        phone:{
            type:type.STRING
        },
        ruc:{
            type:type.STRING,
            primaryKey:true,
        },
        company_name:{
            type:type.STRING
        },
        social_sector:{
            type:type.STRING
        },
        annual_income:{
            type:type.STRING
        },
        name_r:{
            type:type.STRING
        },
        position:{
            type:type.STRING
        },
        typeDocument:{
            type:type.BOOLEAN,
            defaultValue:1
        },
        document:{
            type:type.STRING
        },
        email_r:{
            type:type.STRING
        },
        pep:{
            type:type.BOOLEAN,
            defaultValue:0
        }

    })
}